######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 18 10:08:47 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /ad/eng/users/e/r/ericli21/EC535_Labs/ec535-multi-mp3/Ui/. .

# Input
HEADERS += mybutton.h
SOURCES += main.cpp mybutton.cpp
