######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 23 12:49:55 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /ad/eng/users/e/r/ericli21/EC535_Labs/ec535-multi-mp3/Ui/. .

# Input
HEADERS += mainmenu.h mainwindow.h menu1.h menu2.h mybutton.h
SOURCES += main.cpp mainmenu.cpp mainwindow.cpp menu1.cpp menu2.cpp mybutton.cpp
