######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 18 08:44:37 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /ad/eng/users/e/r/ericli21/EC535_Labs/ec535-multi-mp3/UI/. .

# Input
SOURCES += main.cpp
